Repository acm-ucr/R-Brains, pull requests merged in 2025-05, with the labels that each got.

#21 kellyramirezz/Resource_Services
  src/app/Services/ResourceServices.tsx
Labels: help wanted, question

#43 Added Nav bar
  public/star.png
  src/app/layout.tsx
  src/app/navbar.tsx
Labels: ready to review

#23 Made StarLogo component
  public/StarLogo.webp
  public/psychology-panels.webp
  public/volunteer.webp
  src/components/PsychologyPanel.tsx
  src/components/StarLogo.tsx
  src/components/StarsBottomLayout.tsx
  src/components/Volunteer.tsx
Labels: bug, enhancement

#56 added text and boxes as well as new webpage for opportunities
  src/app/Opportunities/page.tsx
  src/app/components/Club.tsx
  src/app/components/Lab.tsx
  src/app/components/Volunteering.tsx
Labels: ready to review

#62 Made reusable box component.
  src/components/box-component.tsx
Labels: ready to review

#65 Made reusable button component.
  src/components/ReuseableButton.tsx
Labels: ready to review

#40 Implemented the Footer
  package-lock.json
  package.json
  public/board/Abby_Lazar.webp
  public/board/Alexa_Zelaya.webp
  public/board/Angie_Santander.webp
  public/board/Catherine_Sanchez.webp
  public/board/Rishitha_Kona.webp
  public/board/Sagey_Moorjani.webp
  public/board/Shriya_Patel.webp
  src/app/layout.tsx
  src/components/Footer.tsx
  src/components/Navbar.tsx
Labels: ready to review

#72 Added about us, mission statement and how to join section.
  public/quote.webp
  src/app/globals.css
  src/app/homePage.tsx
  src/components/ReusableTitle.tsx
  tailwind.config.ts
Labels: ready to review

#74 Kellyramirezz/home landing
  public/homelanding/TO.svg
  public/homelanding/curvetext.svg
  public/homelanding/heart1.svg
  public/homelanding/heart2.svg
  public/homelanding/heart3.svg
  public/homelanding/rbrainslogo.svg
  public/homelanding/squiggle1.svg
  public/homelanding/squiggle2.svg
  src/app/components/Home/HomeLanding.tsx
  src/app/layout.tsx
Labels: question

#91 Carousel-shadcn
  components.json
  package-lock.json
  package.json
  public/Carousel/carousel1.webp
  public/Carousel/carousel2.webp
  public/Carousel/carousel3.webp
  public/Carousel/carousel4.webp
  public/Carousel/carousel5.webp
  src/components/carousel/carousel.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/carousel.tsx
  src/data/carousel.ts
  src/utils/utils-shad.ts
Labels: ready to review

#95 built resources page with components
  src/components/resources/UCRServices.tsx
Labels: ready to review
