Repository acm-ucr/R-Brains, pull requests merged in 2025-06, with the labels that each got.

#77 added notfound page and images
  public/notfound/Blue.webp
  public/notfound/Purple.webp
  src/app/not-found.tsx
  src/components/NotFound.tsx
Labels: bug, in progress

#94 Made the quote image transparent on the Home page
  public/home/quote.webp
  src/components/about/homePage.tsx
Labels: ready to review

#106 Added Scroll button and load animation.
  package-lock.json
  package.json
  public/home/scroll.webp
  src/app/gallery/page.tsx
Labels: ready to review

#109 Made the stars on the Home page responsive
  public/home/psychology-panelMobile.webp
  public/home/psychology-panels.webp
  public/home/volunteer.webp
  public/home/volunteerMobile.webp
  src/app/page.tsx
  src/components/about/DestressWorkshops.tsx
  src/components/about/PsychologyPanel.tsx
  src/components/about/Volunteer.tsx
Labels: ready to review

#105 Change Link to Button
  src/app/home/page.tsx
  src/components/about/homePage.tsx
Labels: in progress

#112 Added welcome animation.
  package-lock.json
  package.json
  src/components/about/HomeLanding.tsx
Labels: ready to review

#115 made carousel bigger
  src/components/carousel/carousel.tsx
Labels: ready to review
